name: Auto-Release with OpenAI Summaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This gets the full history for parsing commits

      - name: Get previous tag
        id: prevtag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_OUTPUT
          echo "Previous tag: $PREV_TAG"

      - name: Get current tag
        id: curtag
        run: |
          CURRENT_TAG=${GITHUB_REF#refs/tags/}
          echo "CURRENT_TAG=$CURRENT_TAG" >> $GITHUB_OUTPUT
          echo "Current tag: $CURRENT_TAG"

      - name: Extract commit messages
        id: commits
        run: |
          if [ -z "${{ steps.prevtag.outputs.PREV_TAG }}" ]; then
            # If there's no previous tag, get all commits up to the current tag
            COMMITS=$(git log --pretty=format:"%h - %s" ${{ steps.curtag.outputs.CURRENT_TAG }})
          else
            # Get commits between the previous tag and the current tag
            COMMITS=$(git log --pretty=format:"%h - %s" ${{ steps.prevtag.outputs.PREV_TAG }}..${{ steps.curtag.outputs.CURRENT_TAG }})
          fi

          # Save commits to a file to avoid issues with special characters in commit messages
          echo "$COMMITS" > commits.txt
          echo "Commit log created"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate release notes with OpenAI
        id: openai
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Create a separate Python script file
          cat > generate_notes.py << 'EOL'
          import os
          import openai

          # Initialize the OpenAI client
          client = openai.OpenAI(api_key=os.environ["OPENAI_API_KEY"])

          # Read commit messages from file
          with open("commits.txt", "r") as f:
              commits = f.read()

          # Skip if there are no commits
          if not commits.strip():
              print("No new commits found")
              with open("release_notes.md", "w") as f:
                  f.write("No changes in this release")
              with open("release_title.txt", "w") as f:
                  f.write("Maintenance Release")
              exit(0)

          # Generate release notes using OpenAI
          prompt = f"""
          Below is a list of git commits. Please create a well-formatted release notes summary.
          Group the changes into categories (Features, Bug Fixes, Documentation, etc.) and provide a high-level summary.
          Format the output in Markdown.

          Commits:
          {commits}
          """

          response = client.chat.completions.create(
              model="gpt-4o",
              messages=[
                  {"role": "system", "content": "You are a helpful assistant that summarizes git commits into well-structured release notes."},
                  {"role": "user", "content": prompt}
              ],
              temperature=0.7,
              max_tokens=1000,
          )

          # Save the generated release notes to a file
          release_notes = response.choices[0].message.content

          # Remove markdown code block markers if present
          if release_notes.startswith("```markdown"):
              release_notes = release_notes.replace("```markdown", "", 1)
              if release_notes.endswith("```"):
                  release_notes = release_notes[:-3]
          elif release_notes.startswith("```"):
              release_notes = release_notes.replace("```", "", 1)
              if release_notes.endswith("```"):
                  release_notes = release_notes[:-3]
                  
          # Strip any leading/trailing whitespace
          release_notes = release_notes.strip()

          with open("release_notes.md", "w") as f:
              f.write(release_notes)

          # Generate a short title summary
          title_prompt = f"""
          Based on these git commits, create a very short (5-7 words max) summary of the main changes for a release title.
          Focus on the most significant changes. Be concise and informative.

          Commits:
          {commits}
          """

          title_response = client.chat.completions.create(
              model="gpt-4o",
              messages=[
                  {"role": "system", "content": "You are a helpful assistant that creates concise release titles."},
                  {"role": "user", "content": title_prompt}
              ],
              temperature=0.7,
              max_tokens=50,
          )

          # Save the generated title to a file
          release_title = title_response.choices[0].message.content.strip()
          # Remove quotes if present
          if release_title.startswith('"') and release_title.endswith('"'):
              release_title = release_title[1:-1]
          with open("release_title.txt", "w") as f:
              f.write(release_title)

          print("Release notes and title generated successfully")
          EOL

          # Run the Python script
          python generate_notes.py

          # Use GitHub's recommended way to set output for multi-line values
          RELEASE_NOTES=$(cat release_notes.md)
          echo "release_notes<<DELIMITER" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTES" >> $GITHUB_OUTPUT
          echo "DELIMITER" >> $GITHUB_OUTPUT

          # Set the release title as output
          RELEASE_TITLE=$(cat release_title.txt)
          echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: '${{ steps.curtag.outputs.CURRENT_TAG }} - ${{ steps.openai.outputs.release_title }}'
          body: ${{ steps.openai.outputs.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
